# Generated by Django 5.0.3 on 2024-04-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0002_alter_bookcopy_options_alter_bookseries_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookseries',
            name='position_in_series',
        ),
        migrations.AddField(
            model_name='book',
            name='position_in_series',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
