# Generated by Django 5.0.3 on 2024-04-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0003_remove_bookseries_position_in_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subgenre',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
