# Generated by Django 5.0.3 on 2024-04-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0003_alter_genre_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookseries',
            name='author',
        ),
        migrations.AddField(
            model_name='bookseries',
            name='author',
            field=models.ManyToManyField(related_name='series', to='books_api.author'),
        ),
    ]
