# Generated by Django 5.0.3 on 2024-04-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0004_remove_bookseries_author_bookseries_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='books_api.genre'),
        ),
    ]
