# Generated by Django 5.0.3 on 2024-04-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0005_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
