# Generated by Django 5.0.3 on 2024-04-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0006_author_birth_year_author_death_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-date_modified']},
        ),
        migrations.AddField(
            model_name='author',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
