# Generated by Django 5.0.3 on 2024-04-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0009_alter_issue_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='book_status',
            field=models.CharField(choices=[('R', 'Returned'), ('L', 'Lost'), ('I', 'Issued')], default='I', max_length=20),
        ),
    ]
