# Generated by Django 5.0.3 on 2024-04-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0010_alter_issue_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
