# Generated by Django 5.0.3 on 2024-04-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0011_alter_issue_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='check_out_date',
            field=models.DateField(auto_now=True),
        ),
    ]
