# Generated by Django 5.0.3 on 2024-03-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='no_of_copies',
            new_name='available_copies',
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed_copies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='publiser',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
