# Generated by Django 5.0.3 on 2024-03-30 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_author_book_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='sub_genre',
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_genres', to='api.genre')),
            ],
        ),
    ]
