# Generated by Django 5.0.3 on 2024-03-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_genre_sub_genre_subgenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='image_not_found.jpg', upload_to='books'),
        ),
    ]
