# Generated by Django 5.0.3 on 2024-04-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Patron',
        ),
        migrations.RenameField(
            model_name='membershipcard',
            old_name='member',
            new_name='patron',
        ),
    ]
