# Generated by Django 5.0.3 on 2024-04-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_rename_member_patron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
